package com.moma.otasset.dao.mapper;

import com.moma.otasset.dao.domain.AssetUser;
import com.moma.otasset.dao.domain.AssetUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    long countByExample(AssetUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int deleteByExample(AssetUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int insert(AssetUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int insertSelective(AssetUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    List<AssetUser> selectByExample(AssetUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    AssetUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AssetUser record, @Param("example") AssetUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AssetUser record, @Param("example") AssetUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AssetUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AssetUser record);
}