package com.moma.otasset.dao.domain;

import java.math.BigDecimal;
import java.util.Date;

public class AssetUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.huobi_uid
     *
     * @mbg.generated
     */
    private Long huobiUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.asset
     *
     * @mbg.generated
     */
    private BigDecimal asset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_user.u_time
     *
     * @mbg.generated
     */
    private Date uTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.id
     *
     * @return the value of asset_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.id
     *
     * @param id the value for asset_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.huobi_uid
     *
     * @return the value of asset_user.huobi_uid
     *
     * @mbg.generated
     */
    public Long getHuobiUid() {
        return huobiUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.huobi_uid
     *
     * @param huobiUid the value for asset_user.huobi_uid
     *
     * @mbg.generated
     */
    public void setHuobiUid(Long huobiUid) {
        this.huobiUid = huobiUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.nick_name
     *
     * @return the value of asset_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.nick_name
     *
     * @param nickName the value for asset_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.asset
     *
     * @return the value of asset_user.asset
     *
     * @mbg.generated
     */
    public BigDecimal getAsset() {
        return asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.asset
     *
     * @param asset the value for asset_user.asset
     *
     * @mbg.generated
     */
    public void setAsset(BigDecimal asset) {
        this.asset = asset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.c_time
     *
     * @return the value of asset_user.c_time
     *
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.c_time
     *
     * @param cTime the value for asset_user.c_time
     *
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_user.u_time
     *
     * @return the value of asset_user.u_time
     *
     * @mbg.generated
     */
    public Date getuTime() {
        return uTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_user.u_time
     *
     * @param uTime the value for asset_user.u_time
     *
     * @mbg.generated
     */
    public void setuTime(Date uTime) {
        this.uTime = uTime;
    }
}