package com.moma.otasset.dao.domain;

import java.math.BigDecimal;
import java.util.Date;

public class AssetChange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.huobi_uid
     *
     * @mbg.generated
     */
    private Long huobiUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.operation_type
     *
     * @mbg.generated
     */
    private Integer operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.bcoin_asset_change
     *
     * @mbg.generated
     */
    private BigDecimal bcoinAssetChange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.bcoin_asset
     *
     * @mbg.generated
     */
    private BigDecimal bcoinAsset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_change.c_time
     *
     * @mbg.generated
     */
    private Date cTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.id
     *
     * @return the value of asset_change.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.id
     *
     * @param id the value for asset_change.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.huobi_uid
     *
     * @return the value of asset_change.huobi_uid
     *
     * @mbg.generated
     */
    public Long getHuobiUid() {
        return huobiUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.huobi_uid
     *
     * @param huobiUid the value for asset_change.huobi_uid
     *
     * @mbg.generated
     */
    public void setHuobiUid(Long huobiUid) {
        this.huobiUid = huobiUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.nick_name
     *
     * @return the value of asset_change.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.nick_name
     *
     * @param nickName the value for asset_change.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.operation_type
     *
     * @return the value of asset_change.operation_type
     *
     * @mbg.generated
     */
    public Integer getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.operation_type
     *
     * @param operationType the value for asset_change.operation_type
     *
     * @mbg.generated
     */
    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.amount
     *
     * @return the value of asset_change.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.amount
     *
     * @param amount the value for asset_change.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.bcoin_asset_change
     *
     * @return the value of asset_change.bcoin_asset_change
     *
     * @mbg.generated
     */
    public BigDecimal getBcoinAssetChange() {
        return bcoinAssetChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.bcoin_asset_change
     *
     * @param bcoinAssetChange the value for asset_change.bcoin_asset_change
     *
     * @mbg.generated
     */
    public void setBcoinAssetChange(BigDecimal bcoinAssetChange) {
        this.bcoinAssetChange = bcoinAssetChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.bcoin_asset
     *
     * @return the value of asset_change.bcoin_asset
     *
     * @mbg.generated
     */
    public BigDecimal getBcoinAsset() {
        return bcoinAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.bcoin_asset
     *
     * @param bcoinAsset the value for asset_change.bcoin_asset
     *
     * @mbg.generated
     */
    public void setBcoinAsset(BigDecimal bcoinAsset) {
        this.bcoinAsset = bcoinAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_change.c_time
     *
     * @return the value of asset_change.c_time
     *
     * @mbg.generated
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_change.c_time
     *
     * @param cTime the value for asset_change.c_time
     *
     * @mbg.generated
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }
}